### ISSUE TITLE
N terminal peptide modification

### ISSUE THREAD

**Issue by adithirv** [chhh/MSFragger-GUI#10]
Hi, 

I am running a closed search using a set of mgf files. I am interesting in adding a peptide N terminal pyro-glu modifcation to my analysis. But MSFragger freezes after starting the process. There are no error messages given. Could you please guide me as to what may be the problem?
Here is how I define the modification: 'variable_mod_04 = -17.02650 nQ'. Alternatively, I also tested another N terminal peptide modification facing the same problem: 'variable_mod_05 = -17.0106 nE'.

Thanks in advance,
AR

**Comment by chhh** [comment]
@adithirv  
Could you please post here the following:
 - The output that gets printed in the text console (either in GUI or command line console)
 - The fragger parameters file that you use. If you're using the GUI version, this file is written to the output directory that you specify.

**Comment by adithirv** [comment]
@chhh 
Here is the output from the console which stays the same even upto 24 hours (the max time I waited to check for progress before I kill the job).
Will execute 1 commands:
java -jar /home/bioinf/bioinf_data/33_omul/projects/bartonella_henselae/proteogenomics/msfragger_refseq_all/MSFragger/MSFragger_20170103/MSFragger.jar /home/bioinf/bioinf_data/33_omul/projects/bartonella_henselae/proteogenomics/msfragger_refseq_all/msfragger_param1_GUI_mzML/fragger.params /home/bioinf/bioinf_data/33_omul/projects/bartonella_henselae/proteogenomics/msfragger_refseq_all/msfragger_param1_GUI_mzML/cyt1_ogepep.mzML 

~~~~~~~~~~~~~~~~~~~~~~


Executing command:
$> java -jar /home/bioinf/bioinf_data/33_omul/projects/bartonella_henselae/proteogenomics/msfragger_refseq_all/MSFragger/MSFragger_20170103/MSFragger.jar /home/bioinf/bioinf_data/33_omul/projects/bartonella_henselae/proteogenomics/msfragger_refseq_all/msfragger_param1_GUI_mzML/fragger.params /home/bioinf/bioinf_data/33_omul/projects/bartonella_henselae/proteogenomics/msfragger_refseq_all/msfragger_param1_GUI_mzML/cyt1_ogepep.mzML 
Process started

[fragger.params.txt](https://github.com/chhh/MSFragger-GUI/files/1306188/fragger.params.txt)

Thanks,
AR

**Comment by chhh** [comment]
@adithirv There certainly is no need to wait 24h, something is wrong. Could you please provide some info about your environment?
- version of GUI you're using
- OS and version
- is it a 32 or 64 bit system
- the output of `java -version` or better the output in the GUI console, when you click `Check Java Version` button on the `Run` tab.
- which version fragger version do you have (just the name of the zip file you downloaded)

**Comment by adithirv** [comment]
@chhh Here are the details corresponding to your questions, I am using:

- MSFRAGGER GUI v3.0
- Debian 8.4 (jessie codename)
- 64bit
- 1.8.0_121
- MSFragger build 20170103.0

Hope the information helps to resolve what they problem might be. Let me know if you need further information.

Thanks

**Comment by chhh** [comment]
@adithirv 
I don't see a reason for it not to work. We haven't tried it on Debian specifically, but should not matter as long as the `java` command is working.
- What happens if you go to the `Run` tab and click `Check Java Version`? Does it print anything?
- What happens if you try the following command from the terminal `java -jar MSFragger.jar fragger.params some-file.mzML`?

**Comment by adithirv** [comment]
@chhh 

- This is what is printed when I click 'Check Java Version' in the 'Run' tab:
Java Info:
java.version: 1.8.0_121
java.vm.specification.version: 1.8
java.vm.specification.vendor: Oracle Corporation
java.vm.specification.name: Java Virtual Machine Specification
java.vm.version: 25.121-b13
java.vm.vendor: Oracle Corporation
java.vm.name: Java HotSpot(TM) 64-Bit Server VM
java.specification.version: 1.8
java.specification.vendor: Oracle Corporation
java.specification.name: Java Platform API Specification
- It runs fine **only if the output format is pepXML**.

So, I now figured it out that the run goes into sleep when the output format from MSFragger is set to 'tsv' both on the GUI and on the command line. Hope that gives you more insight on what might go wrong here.

**Comment by andytyk** [comment]
The downstream analysis (TPP and Philosopher) is only compatible with the pepXML output.  TSV output is more for getting a quick look at your data or for developers who want to couple MSFragger output to their tools but don't want to deal with the pepXML format.  Let us know if you have any further issues.
