### ISSUE TITLE
decoy proteins

### ISSUE THREAD

**Issue by sdgroeve** [chhh/MSFragger-GUI#11]
Suppose I have a fasta protein with header

>sp|A0A075B6H9|LV469_HUMAN Immunoglobulin lambda variable 4-69 OS=Homo sapiens GN=IGLV4-69 PE=1 SV=1

How do I format the decoy version of this protein in the fasta file? Where do I add a prefix? I don't get it to work.

Thanks

**Comment by chhh** [comment]
Hi @sdgroeve ,
It should be the prefix to the whole ID string, e.g. `rev_sp|A0A...`

**Comment by sdgroeve** [comment]
What I did wrong is setting the --decoy cmd line parameter of PeptideProphet as
-decoy "rev"
while it should be
--decoy rev

thnx!

**Comment by chhh** [comment]
you're welcome
