### ISSUE TITLE
sample data to test installation

### ISSUE THREAD

**Issue by trishorts** [chhh/MSFragger-GUI#14]
it would be wonderful if you could provide sample .mzml, .fasta and .params file to test open search with the gui. This would help establishing that the installation was successful and to separate out troubles associated with the format of other files.

**Comment by chhh** [comment]
Thanks for the suggestion @trishorts , I'll post a link in the readme shortly

**Comment by tomthun** [comment]
Does the link to test the installation still exist?

**Comment by chhh** [comment]
Migrated to #35

**Comment by chhh** [comment]
Closing as duplicate
