### ISSUE TITLE
nonspecific searches generate too many peptides

### ISSUE THREAD

**Issue by bpalanski** [chhh/MSFragger-GUI#17]
For a peptidomics experiment with a nonspecific search, MSFragger is generating too many peptides. It appears that 2^31 - 1 is the maximum number allowed. Are there any planned updates to expand this, or any practical workarounds you can suggest? I am running on a cluster with 1.5 TB RAM and 20 cores, so system resources shouldn't be an issue for me.

**Comment by chhh** [comment]
@bpalanski Can you be more specific please? Do I understand it right that the problem is that too many theoretical peptides are generated from your database? If so:  
- what database are you using?
- what peptide mass range are you allowing?

Could you describe your experiment in a few words?

**Comment by bpalanski** [comment]
Thanks for the speedy response and for any advice.

Yes, too many theoretical peptides are generated from my database. I am allowing peptides of length 6-40, with m/z 500-4700, to be consistent with how I setup the searches in other search engines (MS-GF+ and XTandem). I have allowed cleavage after every amino acid (completely nonspecific). I am searching the wheat proteome (http://www.uniprot.org/proteomes/UP000019116), with decoys appended. If I reduce the allowed length to 12-25 and the peptide mass range to 1000-4700, then the search runs, but this is not ideal.

**Comment by chhh** [comment]
@bpalanski oops, my response hasn't posted for some reason. Let's try again.  
So I was told that limiting the max length to about 30-35 and allowing only 1-2 variable modifications works for Human proteome.  
Have you arrived at those numbers by trial and error? It doesn't work if you up the max length to 30-35?  
Uniprot website indicates that your fasta file has 120k proteins, add 120k decoys, that 240k - that's quite a lot and the problem might be there. But let's diagnose it further first.  

Can you please post the following: 
- How are you running fragger? from the command line or GUI?
- If command line, then what command are you using
- The `fragger.params` file that you're using. If you're using GUI, then the `.params` file can be found in the output directory. Alternatively on the Fragger tab you can click `Save` button to store the settings currently in the form.

**Comment by bpalanski** [comment]
@chhh Yes, I arrived at the numbers by trial and error. I'm pretty sure the problem is that my database is just too big, but here is the requested info:

1. Running fragger from the command line.
2. java -Xmx450G -jar MSFragger.jar 2017_10_02_Wheat_fragger.params /path/to/mzML file (where I have the actual path to my file here). I can go up to 1500G memory but I don't think this will help me.
3. Attached


[2017_10_02_Wheat_fragger.params.txt](https://github.com/chhh/MSFragger-GUI/files/1357844/2017_10_02_Wheat_fragger.params.txt)

**Comment by andytyk** [comment]
@bpalanski I'm afraid the database is just too big.  As you've suspected, giving MSFragger more memory would not help in this case as you're running into a implementation limitation in the maximum number of peptides allowed in the peptide index.  While we can introduce certain hacks to overcome this in a future version of MSFragger, there are no workarounds in the current version.

**Comment by bpalanski** [comment]
@andytyk Thanks Andy, this is what I was afraid of. It would be really great if you could work on this in a future version. When I've tested my nonspecific searches using the human database, I'm getting similar results to X!Tandem and MS-GF+ in just a fraction of the time. Unfortunately for this project I need to be able to search wheat as well. Looking forward to the update!
