### ISSUE TITLE
Installing and running MSFragger Gui 3.0

### ISSUE THREAD

**Issue by trayambakbasak** [chhh/MSFragger-GUI#18]
HI,
could anyone please share a instruction for running the MSFragger GUI 3.0
I have installed but could not get the MSFragger.jar file and thus could not run the GUI to test.

THanks,
Trayambak.

**Comment by chhh** [comment]
@trayambakbasak Why can't you get the MSFragger.jar file? You can start the GUI by running `fragger-gui.bat` on Windows or `fragger-gui.sh` on Linux. You can just double-click. If nothing happens, it means you don't have java installed, but that is unlikely these days.
In the GUI you can click the `Download` button, it should open your browser and point you to the right website. You'll have to agree to license terms to get the link for download.

If that doesn't work for you, open the following link to your browser:  
http://inventions.umich.edu/technologies/7143_msfragger-ultrafast-and-comprehensive-identification-of-peptides-from-tandem-mass-spectra
There click `7143 - MSFragger - Academic and Research Education Use License` link on the right hand side and follow instructions.

**Comment by trayambakbasak** [comment]
Here is the snapshot summary of installing MSFragger.. Still facing problem..

Thanks for your help.

[MSFragger_installation_issues.pptx](https://github.com/chhh/MSFragger-GUI/files/1363442/MSFragger_installation_issues.pptx)

**Comment by chhh** [comment]
@trayambakbasak please save it as a pdf file

**Comment by trayambakbasak** [comment]
PFA
[MSFragger_installation_issues.pdf](https://github.com/chhh/MSFragger-GUI/files/1363782/MSFragger_installation_issues.pdf)

**Comment by chhh** [comment]
@trayambakbasak So it looks like you have downloaded fragger and philosopher, but you didn't specify the paths to them in the GUI. On your last slide you show the `Config` tab. There are two balloon notifications telling you what is wrong with the configuration - it can't find the MSFragger's jar file and Philosopher's executable. Click the `Browse` button for MSFragger and select the `jar` file that you've downloaded. Do the same for Philosopher. It will work then.  

Alternatively you can try clicking `Search Tools` at the top of `Config` tab, and point it to your downloads directory (any place where you've downloaded the tools, or any directory above it), it will try to automatically search for tools. However, manually selecting both the MSFragger's jar and Philsopher's executable is less error prone.

**Comment by trayambakbasak** [comment]
Well I have only contacted you after trying all that. There is no .jar file in the directories and it can not find it. Please take a look at the directories for MSFragger and Philosopher that I downloaded.
[MSFragger_installation_issues.pdf](https://github.com/chhh/MSFragger-GUI/files/1363920/MSFragger_installation_issues.pdf)

**Comment by chhh** [comment]
What do you mean it can not find it? Have you clicked the `Browse` button and selected the file yourself? The text field should change to the full absolute path to the jar file. From what I see - you still have the default MSFragger.jar there.

What happens when you click `Download`? This button doesn't do anything but sending you to the corresponding web page. You must download everything manually (and accept licenses) yourself. If your browser doesn't open by itself, open it manually and download the softawre.  

Here are the links again:  
 - MSFragger: https://secure.nouvant.com/umich/technology/7143/license/633
 - Philosopher: https://github.com/prvst/philosopher/releases/download/1.8/philosopher_windows_amd64.exe

**Comment by rebki** [comment]
Hi,

I have a similar problem.

I can easily select the correct .jar file and the path appears. However, this does not work for the philosopher executable. When I try to select it using the "Browse" button, the path does not appear, instead the default (here philosopher_linux_amd64) remains without the path, and the error message does not disappear.

I'm on Ubuntu 16.04, java openjdk version "1.8.0_151".

**Comment by chhh** [comment]
- Have you tried running the philosopher executable separately to make sure you downloaded the right version for your OS?  
- Have you tried just typing in the correct path?
- another option is to use the "find tools" button at the top and point it to some top level directory containing both philosopher and Fragger, e.g. Downloads

**Comment by rebki** [comment]
Thanks for your answer.

The second two points I had tried already, they did not fix the problem. But I found the solution: Making the executable executable helps of course.

**Comment by chhh** [comment]
@rebki Oh, yeah, I'll add a permissions check, didn't think about that.

**Comment by cksakura** [comment]
Hello,

I have exactly the same problem.
![image](https://user-images.githubusercontent.com/6902434/34540818-f3760dce-f0a3-11e7-9ed1-c310e7b4417d.png)
Nothing happened after I clicked the "Select" button. 
![image](https://user-images.githubusercontent.com/6902434/34540854-1cc5fb1c-f0a4-11e7-8a9a-dd78de7d050e.png)
I have tried the absolute/relative path and no one works.

Thank you.
Kai Cheng

**Comment by chhh** [comment]
Can you please try a newer version? 4.0+

**Comment by chhh** [comment]
Both GUI and Fragger were upgraded, if the issue persists, please open another ticket
