### ISSUE TITLE
MSFragger gives 'X fragments to be searched in 0 slices (0.00GB total)'

### ISSUE THREAD

**Issue by whitleyo** [chhh/MSFragger-GUI#22]
Hello,

I've tried to run MSFragger with a 4 protein FASTA file (Uniprot Format, with decoys appended) against spectra from a sample consisting of the 4 proteins in the FASTA file. While theoretical peptides do appear to be produced, msfragger does not generate any slices of the pepindex through which to search spectra against fragments/precursors.

Here's the output:

Removing duplicates and compacting...
Reduced to 669  peptides in 190ms
Generating modified peptides...DONE in 22ms
Generated 931 modified peptides
Merging peptide pools from threads... DONE in 3ms
Sorting modified peptides by mass...DONE in 2ms
Peptide index written in 215ms
Selected fragment tolerance 0.02 Da and maximum fragment slice size of 10831.99MB
73968 fragments to be searched in 0 slices (0.00GB total)

**Comment by andytyk** [comment]
There is a bug in the current version of MSFragger where it fails to search small FASTA files.  This has been fixed in the beta build.  Please e-mail me at andykong at umich.edu so I can provide you with the beta version.

**Comment by chhh** [comment]
Fixed in newer version
