### ISSUE TITLE
MSFragger iTRAQ modification

### ISSUE THREAD

**Issue by whitleyo** [chhh/MSFragger-GUI#23]
Hello,

I'm currently trying to use MSFragger (not the GUI) with  a human proteome dataset with ITRAQ modifications. I know that MSFragger has an option to exclude spectra within a 0-150 Mz Range, but I'm wondering how MSFragger handles ITRAQ modifications (specified as variable or fixed) in generating a database. More specifically, ITRAQ tags are lost upon CID, and I don't know if MSFragger takes this into account when generating a fragment index.

If you have any recommendations as to how to deal with this sort of problem, that would be greatly appreciated.

Thanks!

**Comment by andytyk** [comment]
The following modifications to your fragger parameter file should allow you to search iTRAQ data:

variable_mod_01 = 15.9949 M
variable_mod_02 = 42.0106 [^
variable_mod_03 = 144.1021 n^

add_K_lysine = 144.1021

**Comment by chhh** [comment]
No response in 1 month, assumed solved
