### ISSUE TITLE
Identifying Large PTMs (E.g. Glycosylation)

### ISSUE THREAD

**Issue by whitleyo** [chhh/MSFragger-GUI#24]
Hello,

I'm wondering whether or not you'd recommend against using a large precursor mass tolerance (i.e. 2000 Da) in an open search. I've tried using this parameter across several datasets that used HCD mediated fragmentation, and when I try downstream analysis with philosopher (i.e. philosopher's peptideprophet and proteinprophet), I have been unable to get any confident protein identifications. Thanks for any input.

**Comment by andytyk** [comment]
We have used large precursor tolerances to identify PTMs of similar sizes.  Getting confident IDs at the protein level may be challenging in such a large search space so it may be best to focus on confident IDs at the peptide or PSM level instead.

**Comment by chhh** [comment]
Unclear, need more input
