### ISSUE TITLE
almost half of hits from decoy database using open search

### ISSUE THREAD

**Issue by runxuan** [chhh/MSFragger-GUI#25]
Hi,

I am running MSFragger on Linux using default open search parameters. The reverse decoy database were generated using DecoyDatabaseBuilder_dist_1.5.47. Decoy label "REV_" were added to the decoy database entries and then concatenated to the original database. The results showed almost half hits from decoy databases. Thus no protein or peptide were identified at 1% FDRs.

Here is an example output of peptide prophet from one of the runs
####
Using Decoy Label "REV".
Decoy Probabilities will be reported.
Using non-parametric distributions
 (X! Tandem) (using Tandem's expectation score for modeling)

init with X! Tandem trypsin 
MS Instrument info: Manufacturer: UNKNOWN, Model: UNKNOWN, Ionization: UNKNOWN, Analyzer: UNKNOWN, Detector: UNKNOWN

INFO: Processing standard MixtureModel ... 
 PeptideProphet  (TPP v5.0.1 Post-Typhoon dev, Build 201705191541-exported (Linux-x86_64)) AKeller@ISB
 read in 0 1+, 134 2+, 313 3+, 33 4+, 2 5+, 0 6+, and 0 7+ spectra.
Initialising statistical models ...
Found 207 Decoys, and 275 Non-Decoys
Iterations: .........10.........20.....
WARNING: Mixture model quality test failed for charge (1+).
WARNING: Mixture model quality test failed for charge (2+).
WARNING: Mixture model quality test failed for charge (3+).
WARNING: Mixture model quality test failed for charge (4+).
WARNING: Mixture model quality test failed for charge (5+).
WARNING: Mixture model quality test failed for charge (6+).
WARNING: Mixture model quality test failed for charge (7+).
model complete after 26 iterations

  - /MSdata/interact-PT8022-9.pep.xml
  - Building Commentz-Walter keyword tree...
  - Searching the tree...
  - Linking duplicate entries...
  - Printing results...
#######

Running MSFragger on Linux using default close search parameters has reduced the proportion of decoy hits. However there are still no protein or peptide were identified by 1% FDRs.

While i have tried to run maxQuant using parameters to comparable close search, 4K+ protein groups were identified. It seems that the MS data is ok in terms of quality. 

The PSM scoring algorithms seems to be quite similar between X! Tandem and Andrometa.

Any suggestions on what might be possible reasons that i could not achieve any peptide ids using MSFragger?

if you need any information for forensics, please let me know. 

Thank you very much!

Best regards,

Runxuan

**Comment by runxuan** [comment]
In the MSFragger paper, it is mentioned that precursor mass correction was carried out using a supplementary tool as part of the MSFragger pipeline. The corrected and calibrated m/z values are written into a calibration file that is integrated in the downstream analysis. 

I didn't notice any calibration files when i run the MSFragger. Have i missed anything here? 

Thanks a lot!

Runxuan

**Comment by adithirv** [comment]
Hi,

I am facing the same issue when searching my proteomics data using default open search parameters. Please find attached the first few lines from the output log file from the MSFragger GUI. Similar to Runxuan, in my case I am getting close to 50% of the hits from Decoy databse.

Please note: I am using a proteogenomics database which contains 52147 proteins in total including contaminants. My Decoy database was generated by reversing the sequences. 
I am using condition specific deep proteomics data enriched for under-represented proteins using corresponding transcriptomics data. In total there are 24 files. 

With the same files, MS-GF+ identifies 1388 proteins at 0.01% PSM FDR.

Any suggestions on what parameters of MSFragger or PeptideProphet should I change.

[open_search_default_params.log](https://github.com/chhh/MSFragger-GUI/files/1482197/open_search_default_params.log)

**Comment by andytyk** [comment]
The precursor mass correction is performed using a tool that is not bundled with the MSFragger package.  We plan to include that tool as part of our to-be-released downstream processing suite.

As for diagnosing the lack of protein IDs, please e-mail me at andykong at umich.edu with your fragger parameter file.

**Comment by runxuan** [comment]
Thanks a lot for your help, Andy. I have sent the parameter files to your email account. Please let me know if you need any other info.

**Comment by adithirv** [comment]
Thanks much for your help. I have sent you the parameter file. Do not hesitate to contact me if you need more information.

**Comment by chhh** [comment]
I guess, solved?

**Comment by runxuan** [comment]
I don't think so. I still could not find any identification with a proper
FDR using open search.
