### ISSUE TITLE
Unable to Run the Search

### ISSUE THREAD

**Issue by freddypradeep** [chhh/MSFragger-GUI#27]
@chhh @andytyk ,
i'm getting error as 
"Invalid Maximum Heap Size:XmxBG
Error:Could not create java virtual machine
Error: A fatal exception has occured .
Program will Exit."
I'm using default params file . 

my system configuration is 8GB RAM , i7 processor. 
please help
emailid :freddypradeep03@gmail.com

**Comment by andytyk** [comment]
The B should be an 8 instead.  It may be preferable to use 6GB (-Xms6G) on a machine with 8GB of memory to ensure that you're not running into swap.

**Comment by freddypradeep** [comment]
Hi Andy Tried with 8,  Tried with 6 i get the same error. am i missing out
anything ?

Regards,
Pradeep Freddy A

**Comment by chhh** [comment]
@freddypradeep I assume you're trying to run it from the command line. 

- Please post here the command you're running and the parameter file.
- Please post the output of the following command: `java -version`
- If you tried using `-Xms` switch (note the `s` at the end, it's for **'s'**tart), as @andytyk suggested, then there MUST be at least this amount of RAM available in the system at the **start** of the application. I don't think you have 6GB of RAM free with the OS, browser and whatnot loaded. So 1st try lowering that number. Then also switch back to using `-Xmx` (the `x` at the end is for ma**'x'**) - that's the max amount the JVM will be using. Or just drop those switches altogether, it should then start with some default values determined by the JVM launcher - we only need to get it to start working and figure out the rest afterwards.
- If nothing works, please try downloading the GUI client for fragger from this repository (https://github.com/chhh/MSFragger-GUI/releases/tag/v3.0). There are 2 scripts in the zip file to start the GUI, or you can start it yourself with `java -jar MSFragger-GUI.jar`. Try using that.

**Comment by chhh** [comment]
No response in 2 weeks, closing
