### ISSUE TITLE
Defaults for open search and change tag for report

### ISSUE THREAD

**Issue by adithirv** [chhh/MSFragger-GUI#28]
Hi,

I want to flag two minor suggestions for the MSFragger_GUI. 

1. I noticed that when one clicks on to load "Defaults Open Search" in MSFragger tab of the GUI, then it loads the default parameters only in the MSFragger tab and Prophet tabs whereas when one clicks "Load Defaults Open Search" in the home tab, then it loads the parameters in all tabs including prophets and **report** tab. I think this difference in the behavior when clicked in the home tab versus the msfragger tab or other tabs could be made uniform. 
Initially, I assumed that it makes no difference between loading default parameters for open or closed search from any tab but this not the case.

2. I realized that if one changes the decoy tag from "rev" to something else (e.g. XXX) in the peptideProphet then it should also be correspondingly changed in the report tag with the option "--tag XXX_". This tag option does not appear by default in the Filter option of the report tab. Not setting this correctly or modifying only in the peptideProphet tab will result in 0 decoys in the output from the "philosopher filter" step and thus in the final output files.

Please excuse me if the above suggestions are already known or flagged.
I would be happy to answer further questions if anything unclear.

Best Regards
Adithi

**Comment by chhh** [comment]
@adithirv Thanks for the suggestions!

**Comment by chhh** [comment]
fixed in the latest [release v4.1](https://github.com/chhh/MSFragger-GUI/releases/tag/v4.1)
