### ISSUE TITLE
Open search not finding the expected modifications

### ISSUE THREAD

**Issue by LasseLorentzen** [chhh/MSFragger-GUI#29]
Hi,

I'm trying out this software on a dataset with a lot of chemically induced modifications, with the majority being +45. Identification of peptides with these mass shits have already been confirmed with other search engines, i.e. MS-GF+ and X!tandem.

Although MSFragger does identify peptides with these mass shifts in closed mode, it fails to do so in the open search (default parameters). However, by setting +45 as an expected modification in the open search (all other parameters being equal), the peptides are again identified.

I hope you can help me find out what is wrong here.

**Comment by anesvi** [comment]
In general, if you find it in closed search with +45 specified as variable, you should find at least some in the open search mode. If the modification is located close to peptide's c-terminus, the open search is not as efficient (since it is based on matching unshifted fragment ion only), but you still should find some. So I do not have an answer to why you are not finding anything. You may have to share some data with us so we can take a look

**Comment by LasseLorentzen** [comment]
Thanks for the response. The modifications are not inherently c-terminal, but rather sits on aromatic residues. 

Here's a dropbox [link ](https://www.dropbox.com/sh/lv1hme5q8oj410y/AAApq2z3EwSjUa6YuIrYqDW_a?dl=0)with the mzML file and the corresponding fasta file I've used so far. Mass tolerance should be about 10 and 20 ppm for MS1 and MS2 respectively.

**Comment by andytyk** [comment]
Would you also share the parameters you used in closed mode that identifies your expected modification?

**Comment by LasseLorentzen** [comment]
Thanks for the quick response. I've added a params file to the dropbox folder.

**Comment by andytyk** [comment]
I ran the open search on my computer and it looks fine.  In open search, the modifications won't be localized and marked as a modification but are instead represented as a mass difference (column 13 in the TSV output).  Sorting the output by the mass differences, I see a number of PSMs with mass differences close to the anticipated mass difference (after accounting for the slight instrument mis-calibration of -0.03).

I also see a large number of other mass differences so you have quite a rich mix of modified peptides in your sample.

**Comment by anesvi** [comment]
We have a calibration tool as a stand alone version now. Perhaps it can be added to MSFragger-GUI. We will make an announcement when it is available.
