### ISSUE TITLE
Enhancement - Spectral counting for each files in report

### ISSUE THREAD

**Issue by videlc** [chhh/MSFragger-GUI#3]
Hi,

When searching multiple LC-MS files at once, let's say, a set of AP-MS experiments, it would be really interesting to get information relative to spectral counting for each proteins in separated columns in report.tsv file. 
Completely made up example : 

```
Protein ID	Total Spectral Count	FILE A Spectral count	FILE B Spectral count
A	75	70	5
B	12	6	6
D	33	3	30
```

This would be pretty useful to extract quantitative information (spectral counting) for further processing like AP-MS enrichment analysis (SAINT/Perseus/etc.) or differentially expressed proteins in different samples in total cells/tissues extracts (treated/untreated /// healthy/mutant).

Best regards,
Vivian

**Comment by chhh** [comment]
@videlc This sounds like an easy addon for reporting in Philosopher

**Comment by andytyk** [comment]
Issue addressed in the philosopher project.
