### ISSUE TITLE
Fragmentation type

### ISSUE THREAD

**Issue by malenasj** [chhh/MSFragger-GUI#30]
Hi, 
Does MSFragger support ETD fragmentation? And if so, where can I select the ion type in the search?

**Comment by andytyk** [comment]
MSFragger does not currently support ETD fragmentation.  We plan to add the necessary ion types in a future release.

**Comment by malenasj** [comment]
Thanks for your fast response. I will test it when the feature is there.

**Comment by ludsinn** [comment]
Dear MSFragger team,

I am after glycopeptides using electron-based ion activation methods and want to use MSFragger Glyco for ID assignment and quant (MS1). From a default "glyco-N-hybrid" workflow search on glycoprotein standards, I get nice hits which match with expectations. However, the spectra themselves seem to suffer from unexpectedly numerous unannotated peaks (besides noise).

So, I wondered if all likely-to-be-oberved fragment ions are actually considered in MSFragger Glyco as of yet.
Thus, I was trying to find a more detailed description of the ion types that MSFragger typically uses but struggled to find it...

The Mascot-Team states here: http://www.matrixscience.com/help/fragmentation_help.html
"Electron Transfer Dissociation and Electron Capture Dissociation generate primarily c, y, z+1, and z+2 ions. In some cases, w ions can also be prominent."

-> Can you please confirm that z+1 and z+2 (not charge states but +1 or +2 Da) are considered when defining z-ions?
-> Do you plan to enable users to look for w-ions as well?

If not (yet), please considers this post a feature request ;-)
Thanks!

**Comment by fcyu** [comment]
>  Can you please confirm that z+1 and z+2 (not charge states but +1 or +2 Da) are considered when defining z-ions?

MSFragger performs deisotoping before matching. So, if there is z+0 and has good isotope pattern, z+1 and z+2 should be gone. And no, we don't consider z+1 and z+2.

> Do you plan to enable users to look for w-ions as well?

Not in the near future. 

I am actually more curious about how to figured out that "_the spectra themselves seem to suffer from unexpectedly numerous unannotated peaks (besides noise)._". Did you do that by using FP-PDV? Also, why do you believe that including z+1, z+2, and w ions would always result in good result?

Best,

Fengchao

**Comment by dpolasky** [comment]
Hi Ludwig,

The "z" ion in MSFragger is the z-dot ion, and no others are considered by default. You can however search for other ions like z+2 (and any other backbone fragments of interest) using the "custom ion series" parameter in MSFragger. The format is: `[ion name]_[terminal]_[mass]`, where name is a string (e.g., z2), terminal is either N or C, and mass is the mass of the ion relative to the sequence mass of the amino acids (same as a regular b ion). 

Best,
Dan

**Comment by ludsinn** [comment]
Hi Dan and Fengchao,

thank you very much for your informative reply. I will test asap and report back to you if needed.

Have a great day!
Ludwig

**Comment by niklevin** [comment]
Hi,

If you don't mind I jump in to add to Ludwig's issue:

I've been recently working with LC-MSMS data, the MS2-level spectra of which were (expectedly) populated by "untypical" fragments, say, y+1, z+1 (where y+0 and z+0 are typically not present at all), and even more exotic ones, such as z-2 or y-2. I understand, adding more fragment types as search parameters usually not only doesn't increase the number of IDs, but very often has an adverse effect. However, I'm really interested in being able to tune the fragment-type search space, so I was hoping to use the "custom ion series" feature described by Dan above, and also by Fengchao in the issue No 720 ([link](https://github.com/Nesvilab/FragPipe/issues/720)). It didn't work though, and the topic starter in issue 720 had the same problem with it I think. See attached the log of the search run, in which I tried to define b* ion type as given in the MSFragger example (see also the screenshot of the settings that I input into the workflow).
[log_2023-07-26_14-43-32.txt](https://github.com/Nesvilab/FragPipe/files/12173486/log_2023-07-26_14-43-32.txt)
![Untitled](https://github.com/Nesvilab/FragPipe/assets/140624495/52a3f7fa-76e7-49cd-a38a-bf34c3e9b681)

Am I missing something? It would be very nice to have this feature in the MSFragger arsenal.

Thank you!
Nikita 

P.S.: MSFragger (and FragPipe) is an amazing software, thank you a lot for your efforts

**Comment by dpolasky** [comment]
Hi Nikita,
You can just define the custom ion series parameter by itself, no need to specify "b*" in the regular fragment ion series parameter. If you remove b* from the Fragment ion series, the search should work.

Best,
Dan

**Comment by niklevin** [comment]
It works now indeed, thank you for clarification; I was misled by the instructions in the FragPipe telling specifically "If you define custom series, you will need to include the name you gave it here [i.e., in Fragment ion series]."

Am I right in assuming that any mass shift specified by the user will be applied to all N- (or C-) terminal main-series fragments regardless of their type? The instructions say: "... b* is the equivalent of an N-terminal **_b-ion_** with ammonia loss...", which is a bit confusing.

Thank you again!
Nikita

**Comment by dpolasky** [comment]
I see, thanks for the feedback - we will update the tutorial to clarify. And no, a custom ion series is applied only to the specified ion type, not all N-terminal (or C-terminal) ions. So for example, specifying `b* N -17.026` as a custom ion in addition to `b,c,y,z` in the main Fragment ion series parameter would result in searching for b, b-17, c, y, and z ions, but NOT c-17 ions. To also search c-17 (for example), you would need to specify an additional custom series with the correct mass for a c-ion shift (i.e., the mass of the ammonia loss added to the delta mass for a c-ion). 

Best,
Dan
