### ISSUE TITLE
MSFragger v2.3

### ISSUE THREAD

**Issue by fazeliniah** [chhh/MSFragger-GUI#36]
Hi Dmitry,
I have downloaded the new version (v4.3) for windows. Unfortunately it doesn't start after running the .exe file or the jar file. I didn't have this problem with v4.2. Any help is greatly appreciated.
Thanks

**Comment by chhh** [comment]
@fazeliniah Sorry about that, I've accidentally uploaded wrong jar and exe files. Please [re-download 4.3](https://github.com/chhh/MSFragger-GUI/releases/tag/v4.3), it should work fine now. Sorry about that.
