### ISSUE TITLE
'mv' is not recognized as an internal or external command

### ISSUE THREAD

**Issue by fazeliniah** [chhh/MSFragger-GUI#37]
Trying the new version of MSFragger (V4.3) with updated version of Philosopher (philosopher_windows_386) on win7 (the log file is attached). I believe the philosopher is not compatible with windows.  Any thoughts? This is similar error to the issue that I had with DIA-umpire GUI. Hope there is a fix. Thank you for doing such a great work. 
Cleaning the philosopher work space and MSFragger cache doesn't fix the problem for me. 
[MSFragger_error.txt](https://github.com/chhh/MSFragger-GUI/files/1664502/MSFragger_error.txt)

**Comment by chhh** [comment]
Yeah, others have also reported it, we're looking for a solution. Looks like the problem might be Win7 specific.  
Do you have the option to try running it on another Win version, e.g. Win10 just for confirmation? I ran it on my Win10 with [this philosopher version (20180123)](https://github.com/prvst/philosopher/releases/tag/20180123) and looks ok.

I've opened the issue in philosopher repo: prvst/philosopher#12

**Comment by chhh** [comment]
@fazeliniah Please try [this new one](https://github.com/prvst/philosopher/releases/tag/20180125), hopefully it should fix the issue

**Comment by fazeliniah** [comment]
Thank you for the quick fix. It runs beautifully and fast :) There is no error to report. Thank you and Filpe for this.

**Comment by chhh** [comment]
Awesome!
