### ISSUE TITLE
How to download the latest MSFragger version?

### ISSUE THREAD

**Issue by bittremieux** [chhh/MSFragger-GUI#43]
I have previously signed the license agreement to download the then-current `20170103` version of MSFragger. I saw now that a version `11282017` seems to be available, presumably with some bug fixes and/or improvements (although a changelog seems to be missing).

However, when I try to download this latest MSFragger version the Nouvant system (correctly) reports that I have already signed the license agreement in the past and I'm directed to their site to download again. Unfortunately the link there still refers to the older version I originally downloaded and I can't see any options to change the version.

How can I still updated my MSFragger to the latest version?

**Comment by andytyk** [comment]
This seems to be a bug with the Tech Transfer's licensing provider, I'll get in touch with them to fix it. In the meantime, can you e-mail me at andykong at umich.edu so I can provide you with the updated binary?
