### ISSUE TITLE
Add n-term and c-term modification parameters to MSFragger-GUI 

### ISSUE THREAD

**Issue by anesvi** [chhh/MSFragger-GUI#49]
fragger.params file has the following parameters for specifying fixed modifications that are currently not shown in the GUI. We need to add them:

add_Cterm_peptide = 0.0
add_Nterm_peptide = 0.0
add_Cterm_protein = 0.0
add_Nterm_protein = 0.0

Alexey

**Comment by chhh** [comment]
Don't they show up at the top of the list for additional mods like in the screenshot below?

![fixed-mods](https://user-images.githubusercontent.com/107902/37538592-52201e26-290e-11e8-8bc6-61f38d059ef5.png)

**Comment by anesvi** [comment]
Ok, I see them now, they do.  I must have been staring a computer screen for way too long… Close this ticket.
**********************************************************
Electronic Mail is not secure, may not be read every day, and should not be used for urgent or sensitive issues

**Comment by chhh** [comment]
@anesvi I will also rename that section to "Fixed modifications".
