### ISSUE TITLE
Philosopher produces empty report

### ISSUE THREAD

**Issue by fazeliniah** [chhh/MSFragger-GUI#5]
Hi Dmitry,
I am trying to get MSFragger-GUI to work. It generates the PeptideProphet and ProteinProphet files. The problem occurs when Philosopher is trying to generate the reports. The fatal error is "Cannot identify the database type " and "Database data not available, interrupting processing". What do you think the problem is? I have attached my log file for your review. The files are also available if you are interested to check them. 
Thanks
H
[Msfragger_log_20170620.txt](https://github.com/chhh/MSFragger-GUI/files/1088833/Msfragger_log_20170620.txt)

**Comment by fazeliniah** [comment]
I found out what the issue is. It was because of the formatting of my decoy database. I used philosopher to generate the database and that fixed the problem. 
Now my question is about visualization of the data generated at different stage using MSFragger-GUI. Is Batmass helpful to visualize this data? If so, is there any tutorial on that?
H

**Comment by chhh** [comment]
Hi @fazeliniah ,
We're aware of problems with database formatting (to generate proper protein level reports, Philosopher requires a well formatted DB). We're working toward a solution to make the pipeline more compatible with custom databases that people use.

Which data are you referring to in particular? I'm currently building a tool that allows to visualize open search results - you can plot distributions of various delta masses, and see what peptides contributed to which delta masses, see spectra etc. But this is not finished yet.

BatMass can help you visualize detected peptides by overlaying them onto a 2D map of an LC/MS experiment. This is to give you a rough idea of how good your data is - overlay MS2 events on a 2D map, see if there are there a lot of features in LCMS data that were not identified, etc. A tutorial for that sort of use is here: http://www.batmass.org/tutorial/overlay-peptide-ids-on-map2d/

**Comment by chhh** [comment]
@fazeliniah has the issue been resolved?

**Comment by fazeliniah** [comment]
Yes. Thanks!

Sent from my iPhone

On Jun 29, 2017, at 1:18 PM, Dmitry Avtonomov <notifications@github.com<mailto:notifications@github.com>> wrote:


@fazeliniah<https://github.com/fazeliniah> has the issue been resolved?

-

**Comment by chhh** [comment]
Cool!
