### ISSUE TITLE
Add mass_offsets parameter to the GUI

### ISSUE THREAD

**Issue by anesvi** [chhh/MSFragger-GUI#50]
MSFragger parameters file has a 'mass_offsets' parameter. It implements the same functionality as the Comet's option with the same name. 

Mass_offsets in MSFragger creates multiple precursor tolerance windows with
specified mass offsets. These values are multiplexed with the isotope error option. For example,
mass_offsets = 0/79.966 can be used as a restricted ‘open’ search that looks for unmodified and
phosphorylated peptides (on any residue). Setting isotope_error to 0/1/2 in combination with this example will create search windows around (0,1,2,79.966, 80.966, 81.966).
 
It is currently missing in the GUI interface.

Alexey

**Comment by chhh** [comment]
But this is not yet available in the public version of fragger?

**Comment by chhh** [comment]
Added in the latest development version.
