### ISSUE TITLE
Error when searching .mgf files

### ISSUE THREAD

**Issue by LasseLorentzen** [chhh/MSFragger-GUI#8]
Hi, 

I wanted to search some .mgf files using your software. Running MSfragger alone (i.e. without Peptide/ProteinProphet and Philosopher) using MSfraggerGUI, it fails with the following errors: 
```
Will execute 1 commands:
java -jar D:\Data\Lasse\NitroLaminin\Lam_ONOOH_DDA_3\test5\MSFragger.jar D:\Data\Lasse\NitroLaminin\Lam_ONOOH_DDA_3\test5\fragger.params D:\Data\Lasse\NitroLaminin\Lam_ONOOH_DDA_3\test5\100X_A_RA5_01_941.mgf 

~~~~~~~~~~~~~~~~~~~~~~


Executing command:
$> java -jar D:\Data\Lasse\NitroLaminin\Lam_ONOOH_DDA_3\test5\MSFragger.jar D:\Data\Lasse\NitroLaminin\Lam_ONOOH_DDA_3\test5\fragger.params D:\Data\Lasse\NitroLaminin\Lam_ONOOH_DDA_3\test5\100X_A_RA5_01_941.mgf 
Process started
Peptide index read in 317ms
Selected fragment tolerance 0.10 Da and maximum fragment slice size of 1995.85MB

Exception in thread "main" java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.jdt.internal.jarinjarloader.JarRsrcLoader.main(JarRsrcLoader.java:58)
Caused by: java.io.EOFException
	at java.io.RandomAccessFile.readInt(Unknown Source)
	at m.a(Unknown Source)
	at MSFragger.main(Unknown Source)
	... 5 more

871218620 fragments to be searched in 4 slices (6.49GB total)

Process finished, exit value: 1

=========================
===
===        Done
===
=========================
```
I have previously searched this mgf file with X!tandem with no issues, so the file should not be corrupted. 

I hope you can help solve this issue, as I would really like to use this software.

Thank you in advance,
Lasse

**Comment by chhh** [comment]
@LasseLorentzen 
Hi Lasse,
could you please post a link to your mgf file here or maybe share via email?

**Comment by LasseLorentzen** [comment]
Here's the mgf: https://www.dropbox.com/s/kr7r0l21v2ejqwu/100X_A_RA5_01_941.mgf?dl=0

**Comment by andytyk** [comment]
Seems that you've managed to get things up and running in some of our later correspondence so I'm closing this ticket.

**Comment by HANWANQING** [comment]
I tried to use .mgf file just like you did and met the same problems. How did you solve it?

**Comment by fcyu** [comment]
@HANWANQING Could you change the MGF file's line ending to LF and try again?

Thanks,

Fengchao
