### ISSUE TITLE
Errors in default ProteinProphet parameters

### ISSUE THREAD

**Issue by andytyk** [chhh/MSFragger-GUI#9]
For --maxppmdiff, the argument only accepts integers so the ProteinProphet component of Philosopher errors out when given 20.0 (the default parameters in the GUI).  This should be changed to 20.

> Process started
> Error: invalid argument "20.0" for "--maxppmdiff" flag: strconv.ParseUint: parsing "20.0": invalid syntax
> Usage:

**Comment by chhh** [comment]
I can only wonder why did it work before. And also why it only accepts integers...

**Comment by chhh** [comment]
fixed in v2.9
